import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-[rgb(241,241,241)]  text-black h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-thin scrollbar-track-gray-400/5 scrollbar-thumb-[rgb(107,43,43)]/80 pt-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />

    <section id="hero" className='snap-center '>
      <Hero />

    </section>

    <section id='about' className=' snap-center'>
      <About />
    </section>

    {/* <section id="experience" className='snap-center'>
      <WorkExperience />
    </section>

    <section id="skills" className='snap-center'>
      <Skills />
    </section> */}
    
    <section id="projects" className='snap-center'>
      <Projects />
      </section> 

    <section id="contact" className='snap-center'>
      <Contact />
    </section>
    </div>
  )
}
