import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='scroll-smooth bg-[rgb(241,241,241)] dark:bg-[rgb(36,36,36)] dark:text-white inset-0 h-screen sm:snap-y sm:snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-thin scrollbar-track-gray-400/5 scrollbar-thumb-[rgb(107,43,43)]/80 py-2 sm:p-5'>
      <Head>
        <title>Faith Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.imgur.com/QC0SQmO.png" />
      </Head>
    <Header />

    <section id="hero" className='sm:snap-center '>
      <Hero />

    </section>

    <section id='about' className='sm:snap-center'>
      <About />
    </section>

  

    {/* <section id="skills" className='snap-center'>
      <Skills />
    </section> */}
    
    <section id="projects" className='sm:snap-center'>
      <Projects />
      </section> 

      {/* <section id="education" className='snap-center'>
      <WorkExperience />
    </section> */}
    <section id="contact" className='sm:snap-center'>
      <Contact />
    </section>
{/* 
    <Link href="/">
      <footer className='sticky bottom-5 w-fit right-0 cursor-pointer'>
        <div className=' px-5'>
          <img 
            className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer'
            src="https://i.imgur.com/XbHhV15.png"
            alt="profile pic"
            />
        </div>
      </footer>
    </Link> */}
    </div>
  )
}
